--!strict
return {
    RollCycleCount = 10,
    RollCycleMultiplier = 2,
    RollCycleDelay = 0.08,
    ResultHoldSeconds = 1.25,
    RollSlotCount = 5,
    RollCenterSlot = 3,
    RollSpinDuration = 2.1,
    RollSlotSpacing = 0.14,
    RollFadeStartY = 0.5,
    RollFadeEndY = 0.8,
    RollRevealStartScale = 0.92,
    RollRevealPeakScale = 1.08,
    RollRevealPopDuration = 0.18,
    RollRevealSettleDuration = 0.14,
    RollFadeOutDuration = 0.18,
    RollFadeOutOffset = 0.04,
    RollPreviewPadding = 6,
    DefaultRollSoundId = "rbxassetid://0",
    DefaultRollAnimationId = "rbxassetid://0",
}
