--!strict
return {
    {
        Id = "LuckySlime",
        DisplayName = "Lucky Slime",
        Rarity = "Common",
        Weight = 45,
        Zone = "Normal",
        ModelName = "LuckySlime",
        Icon = "rbxassetid://0",
        DisplayOdds = "1 in 2",
        RewardCoins = 2,
    },
    {
        Id = "CloverFox",
        DisplayName = "Clover Fox",
        Rarity = "Uncommon",
        Weight = 24,
        Zone = "Normal",
        ModelName = "CloverFox",
        Icon = "rbxassetid://0",
        DisplayOdds = "1 in 4",
        RewardCoins = 4,
    },
    {
        Id = "CandyComet",
        DisplayName = "Candy Comet",
        Rarity = "Rare",
        Weight = 14,
        Zone = "Candy",
        ModelName = "CandyComet",
        Icon = "rbxassetid://0",
        DisplayOdds = "1 in 8",
        RewardCoins = 8,
    },
    {
        Id = "SugarDrake",
        DisplayName = "Sugar Drake",
        Rarity = "Epic",
        Weight = 7,
        Zone = "Candy",
        ModelName = "SugarDrake",
        Icon = "rbxassetid://0",
        DisplayOdds = "1 in 15",
        RewardCoins = 16,
    },
    {
        Id = "SolarSprite",
        DisplayName = "Solar Sprite",
        Rarity = "Rare",
        Weight = 10,
        Zone = "Gold",
        ModelName = "SolarSprite",
        Icon = "rbxassetid://0",
        DisplayOdds = "1 in 10",
        RewardCoins = 14,
    },
    {
        Id = "GoldTitan",
        DisplayName = "Gold Titan",
        Rarity = "Legendary",
        Weight = 4,
        Zone = "Gold",
        ModelName = "GoldTitan",
        Icon = "rbxassetid://0",
        DisplayOdds = "1 in 30",
        RewardCoins = 30,
    },
    {
        Id = "CrystalRook",
        DisplayName = "Crystal Rook",
        Rarity = "Epic",
        Weight = 6,
        Zone = "Diamond",
        ModelName = "CrystalRook",
        Icon = "rbxassetid://0",
        DisplayOdds = "1 in 20",
        RewardCoins = 28,
    },
    {
        Id = "PrismPhoenix",
        DisplayName = "Prism Phoenix",
        Rarity = "Mythic",
        Weight = 2.5,
        Zone = "Diamond",
        ModelName = "PrismPhoenix",
        Icon = "rbxassetid://0",
        DisplayOdds = "1 in 60",
        RewardCoins = 60,
    },
    {
        Id = "AuroraManta",
        DisplayName = "Aurora Manta",
        Rarity = "Legendary",
        Weight = 3,
        Zone = "Rainbow",
        ModelName = "AuroraManta",
        Icon = "rbxassetid://0",
        DisplayOdds = "1 in 45",
        RewardCoins = 55,
    },
    {
        Id = "SpectrumHydra",
        DisplayName = "Spectrum Hydra",
        Rarity = "Mythic",
        Weight = 1.5,
        Zone = "Rainbow",
        ModelName = "SpectrumHydra",
        Icon = "rbxassetid://0",
        DisplayOdds = "1 in 90",
        RewardCoins = 90,
    },
    {
        Id = "MoltenGolem",
        DisplayName = "Molten Golem",
        Rarity = "Legendary",
        Weight = 2,
        Zone = "Vulcan",
        ModelName = "MoltenGolem",
        Icon = "rbxassetid://0",
        DisplayOdds = "1 in 75",
        RewardCoins = 120,
    },
    {
        Id = "InfernoSeraph",
        DisplayName = "Inferno Seraph",
        Rarity = "Divine",
        Weight = 0.8,
        Zone = "Vulcan",
        ModelName = "InfernoSeraph",
        Icon = "rbxassetid://0",
        DisplayOdds = "1 in 250",
        RewardCoins = 250,
    },
}
